## Basic data science libraries imported

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

## Loading breast cancer data set for binary classification and also imported all the sklearn preprocessing and models

### About the Breast Cancer Dataset

Breast Cancer Wisconsin Dataset is one of the most popular datasets for practicing classification algorithms, especially Binary Logistic Regression.

`Objective`

Predict whether a breast tumor is:

    0 → Malignant (Cancerous)
    1 → Benign (Non-cancerous)

This makes it a binary classification problem because there are only two classes.

    Dataset Size
    Total samples: 569
    Number of features: 30
    Target classes: 2

In [31]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [3]:
data = load_breast_cancer()

In [7]:
X = pd.DataFrame(data.data,
                 columns=data.feature_names)

In [6]:
y = pd.Series(data.target)

In [8]:
X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [9]:
X.shape

(569, 30)

In [ ]:
X.value_counts()

<bound method Series.sum of mean radius  mean texture  mean perimeter  mean area  mean smoothness  mean compactness  mean concavity  mean concave points  mean symmetry  mean fractal dimension  radius error  texture error  perimeter error  area error  smoothness error  compactness error  concavity error  concave points error  symmetry error  fractal dimension error  worst radius  worst texture  worst perimeter  worst area  worst smoothness  worst compactness  worst concavity  worst concave points  worst symmetry  worst fractal dimension
28.110       18.47         188.50          2499.0     0.11420          0.15160           0.32010         0.159500             0.1648         0.05525                 2.8730        1.4760         21.980           525.600     0.013450          0.027720           0.06389          0.014070              0.04783         0.004476                 28.110        18.47          188.50           2499.0      0.11420           0.15160            0.32010          0.15950               0.1648          0.05525                    1
6.981        13.43         43.79           143.5      0.11700          0.07568           0.00000         0.000000             0.1930         0.07818                 0.2241        1.5080         1.553            9.833       0.010190          0.010840           0.00000          0.000000              0.02659         0.004100                 7.930         19.54          50.41            185.2       0.15840           0.12020            0.00000          0.00000               0.2932          0.09382                    1
7.691        25.44         48.34           170.4      0.08668          0.11990           0.09252         0.013640             0.2037         0.07751                 0.2196        1.4790         1.445            11.730      0.015470          0.064570           0.09252          0.013640              0.02105         0.007551                 8.678         31.89          54.49            223.6       0.15960           0.30640            0.33930          0.05000               0.2790          0.10660                    1
7.729        25.49         47.98           178.8      0.08098          0.04878           0.00000         0.000000             0.1870         0.07285                 0.3777        1.4620         2.492            19.140      0.012660          0.009692           0.00000          0.000000              0.02882         0.006872                 9.077         30.92          57.17            248.0       0.12560           0.08340            0.00000          0.00000               0.3058          0.09938                    1
7.760        24.54         47.92           181.0      0.05263          0.04362           0.00000         0.000000             0.1587         0.05884                 0.3857        1.4280         2.548            19.150      0.007189          0.004660           0.00000          0.000000              0.02676         0.002783                 9.456         30.37          59.16            268.6       0.08996           0.06444            0.00000          0.00000               0.2871          0.07039                    1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ..
8.878        15.49         56.74           241.0      0.08293          0.07698           0.04721         0.023810             0.1930         0.06621                 0.5381        1.2000         4.277            30.180      0.010930          0.028990           0.03214          0.015060              0.02837         0.004174                 9.981         17.70          65.27            302.0       0.10150           0.12480            0.09441          0.04762               0.2434          0.07431                    1
8.734        16.84         55.27           234.3      0.10390          0.07428           0.00000         0.000000             0.1985         0.07098                 0.5169        2.0790         3.167            28.850      0.015820          0.019660           0.00000          0.000000              0.01865         0.006736                 10.170        22.80          64.01            317.0       0.14600           0.13100            0.00000          0.00000               0.2445          0.08865                    1
8.726        15.83         55.84           230.9      0.11500          0.08201           0.04132         0.019240             0.1649         0.07633                 0.1665        0.5864         1.354            8.966       0.008261          0.022130           0.03259          0.010400              0.01708         0.003806                 9.628         19.62          64.48            284.4       0.17240           0.23640            0.24560          0.10500               0.2926          0.10170                    1
8.671        14.45         54.42           227.2      0.09138          0.04276           0.00000         0.000000             0.1722         0.06724                 0.2204        0.7873         1.435            11.360      0.009172          0.008007           0.00000          0.000000              0.02711         0.003399                 9.262         17.04          58.36            259.2       0.11620           0.07057            0.00000          0.00000               0.2592          0.07848                    1
8.618        11.79         54.34           224.5      0.09752          0.05272           0.02061         0.007799             0.1683         0.07187                 0.1559        0.5796         1.046            8.322       0.010110          0.010550           0.01981          0.005742              0.02090         0.002788                 9.507         15.40          59.90            274.9       0.17330           0.12390            0.11680          0.04419               0.3220          0.09026                    1
Name: count, Length: 569, dtype: int64>

In [17]:
y.value_counts()

1    357
0    212
Name: count, dtype: int64

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [14]:
X.describe()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [19]:
# Since Logistic Regression uses gradients and features have different scales:

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
# Train Logistic Regression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [24]:
y_pred = model.predict(X_test)

In [32]:
accuracy_score(y_test, y_pred)

0.9736842105263158

In [27]:
confusion_matrix(y_test, y_pred)

array([[41,  2],
       [ 1, 70]])

In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

In [30]:
model.predict_proba(X_test)

array([[1.13590250e-01, 8.86409750e-01],
       [9.99990991e-01, 9.00936206e-06],
       [9.96920905e-01, 3.07909541e-03],
       [5.10134225e-04, 9.99489866e-01],
       [6.06389713e-05, 9.99939361e-01],
       [1.00000000e+00, 9.48087773e-11],
       [9.99999998e-01, 1.53672648e-09],
       [9.65096937e-01, 3.49030633e-02],
       [3.79342140e-01, 6.20657860e-01],
       [7.59402734e-04, 9.99240597e-01],
       [4.98717826e-02, 9.50128217e-01],
       [9.87592879e-01, 1.24071210e-02],
       [6.07381873e-03, 9.93926181e-01],
       [8.56069117e-01, 1.43930883e-01],
       [1.62175599e-03, 9.98378244e-01],
       [9.99259818e-01, 7.40182295e-04],
       [1.85245908e-03, 9.98147541e-01],
       [1.11662359e-05, 9.99988834e-01],
       [8.18375684e-07, 9.99999182e-01],
       [9.99998883e-01, 1.11701472e-06],
       [8.41633901e-02, 9.15836610e-01],
       [9.74778299e-03, 9.90252217e-01],
       [9.99999996e-01, 4.33732393e-09],
       [7.89186669e-05, 9.99921081e-01],
       [1.13874333e-03, 9.98861257e-01],
       [5.84587240e-04, 9.99415413e-01],
       [1.07444521e-03, 9.98925555e-01],
       [5.97518345e-03, 9.94024817e-01],
       [2.85311713e-03, 9.97146883e-01],
       [9.99991817e-01, 8.18296669e-06],
       [5.17409813e-04, 9.99482590e-01],
       [1.48760128e-04, 9.99851240e-01],
       [2.16094439e-03, 9.97839056e-01],
       [5.49413839e-03, 9.94505862e-01],
       [1.40706288e-04, 9.99859294e-01],
       [2.42334266e-03, 9.97576657e-01],
       [9.42415985e-01, 5.75840151e-02],
       [2.89870352e-03, 9.97101296e-01],
       [9.99911214e-01, 8.87859084e-05],
       [4.81363757e-02, 9.51863624e-01],
       [7.12433090e-05, 9.99928757e-01],
       [9.99593392e-01, 4.06608387e-04],
       [2.46640626e-03, 9.97533594e-01],
       [9.63884505e-04, 9.99036115e-01],
       [1.99892051e-02, 9.80010795e-01],
       [7.15547342e-02, 9.28445266e-01],
       [3.98571939e-04, 9.99601428e-01],
       [4.90625569e-04, 9.99509374e-01],
       [3.04698010e-02, 9.69530199e-01],
       [6.14016147e-04, 9.99385984e-01],
       [9.99879654e-01, 1.20346382e-04],
       [9.99999947e-01, 5.31315374e-08],
       [3.08211520e-01, 6.91788480e-01],
       [1.32293769e-02, 9.86770623e-01],
       [2.73627242e-05, 9.99972637e-01],
       [9.54524359e-03, 9.90454756e-01],
       [1.12878558e-04, 9.99887121e-01],
       [1.00000000e+00, 7.32867884e-12],
       [8.35573090e-01, 1.64426910e-01],
       [1.39239947e-04, 9.99860760e-01],
       [5.01360363e-03, 9.94986396e-01],
       [9.99999551e-01, 4.49298134e-07],
       [9.99999999e-01, 1.41043187e-09],
       [3.11060472e-02, 9.68893953e-01],
       [8.29093869e-04, 9.99170906e-01],
       [1.29799229e-01, 8.70200771e-01],
       [9.99986074e-01, 1.39261556e-05],
       [9.99999998e-01, 2.33182543e-09],
       [8.08574976e-04, 9.99191425e-01],
       [2.03813936e-02, 9.79618606e-01],
       [9.98672791e-01, 1.32720921e-03],
       [9.98391518e-01, 1.60848225e-03],
       [2.57408198e-03, 9.97425918e-01],
       [9.95464446e-01, 4.53555363e-03],
       [8.88214751e-05, 9.99911179e-01],
       [1.07439170e-02, 9.89256083e-01],
       [1.99896261e-02, 9.80010374e-01],
       [4.84826685e-01, 5.15173315e-01],
       [2.73957683e-05, 9.99972604e-01],
       [1.38486719e-02, 9.86151328e-01],
       [9.95694507e-01, 4.30549314e-03],
       [6.41710880e-05, 9.99935829e-01],
       [7.76680319e-01, 2.23319681e-01],
       [9.99999990e-01, 9.88915307e-09],
       [9.96105761e-01, 3.89423893e-03],
       [9.98885757e-01, 1.11424341e-03],
       [9.99862833e-01, 1.37167497e-04],
       [9.99859961e-01, 1.40038694e-04],
       [2.19094654e-04, 9.99780905e-01],
       [3.40785200e-03, 9.96592148e-01],
       [5.60602140e-03, 9.94393979e-01],
       [3.22718096e-01, 6.77281904e-01],
       [3.42520227e-02, 9.65747977e-01],
       [2.87072455e-04, 9.99712928e-01],
       [3.90422253e-04, 9.99609578e-01],
       [1.31057534e-04, 9.99868942e-01],
       [9.99999327e-01, 6.73413336e-07],
       [9.99999017e-01, 9.82503124e-07],
       [8.17839564e-05, 9.99918216e-01],
       [9.99669765e-01, 3.30234913e-04],
       [9.96854238e-01, 3.14576223e-03],
       [1.58369703e-06, 9.99998416e-01],
       [9.99983538e-01, 1.64625000e-05],
       [9.99398270e-01, 6.01729959e-04],
       [9.90653170e-03, 9.90093468e-01],
       [3.49633955e-02, 9.65036604e-01],
       [5.75366578e-03, 9.94246334e-01],
       [1.00000000e+00, 1.21896394e-10],
       [1.13099081e-01, 8.86900919e-01],
       [3.21954313e-02, 9.67804569e-01],
       [9.99323175e-01, 6.76825173e-04],
       [1.30828400e-03, 9.98691716e-01],
       [5.42699821e-01, 4.57300179e-01],
       [1.00000000e+00, 7.35106067e-13]])